### ISSUE TITLE
Add LONG_ARRAY type

### ISSUE THREAD

**Issue by WilliamQiufeng** [majestic53/libanvil#3]
There is no switch case or class for **LONG_ARRAY**, causing the error "Unknown tag type" on parsing **OCEAN_FLOOR** tag in .mca region file

**Comment by WilliamQiufeng** [comment]
Btw, what versions are supported now? I tested it on 1.13 and 1.14.2 levels and all results are either empty or chunk not filled.

**Comment by majestic53** [comment]
Merged in. Thanks

> Btw, what versions are supported now? I tested it on 1.13 and 1.14.2 levels and all results are either empty or chunk not filled.

Not sure. I haven't tried this code in years. Last I checked it was working with beta maps (<v.1).
