### ISSUE TITLE
Unexpected end of stream in Minecraft 1.15.2 files

### ISSUE THREAD

**Issue by siarsky** [majestic53/libanvil#6]
The library can not handle all Minecraft 1.15.2 files properly and breaks reading of some files somewhere in the middle.

How to reproduce:
Run libanvil on the file in the attachment.

[r.-1.1.mca.zip](https://github.com/majestic53/libanvil/files/4432508/r.-1.1.mca.zip)

**Comment by majestic53** [comment]
Hi siarsky,

Thanks for your interest in this project.

I looked into the issue you were seeing and put a patch in b062732c64cc2819931b0ae1dc7d24bd01b674a6

**Root-cause (two issues)**

1. The mca file handle got into a EOF state after reading chunk 470, and was no longer returning correct chunk data. As a result, chunk 473 failed to inflate. During inflation, zlib returns Z_DATA_ERROR (-3).
2. The inflation routine return value was not being checked, resulting in undefined behavior.

**Details**
Decompressing chunk 470 causes chunk 473 to not inflate (using zlib) properly. As a result, chunk 473 is left deflated when it's passed into the parser. This causes undefined behavior in the parser, resulting in the error. Inflating chunk 473 on it's own is sucessful.

**Fix**

1. Clear the mca file handle before reading in each deflated chunk.
2. Return an exception if the inflate routine fails

BR,
David J

**Comment by siarsky** [comment]
Hi David,

thanks for your fast response! The library is really very well written and I confirm, this issue does not exist anymore after your new patch.

Thanks
Brani

**Comment by fei2020** [comment]
Thanks for your exciting work.
I have tried your example and get "Unexpected end of stream" exception to work with these mca files in the world packages in the attachment below.
ps. I have tested these world packages in minecraft 1.8.9 & 1.15.2. They all can work.
[SilentReservoir.zip](https://github.com/majestic53/libanvil/files/4766057/SilentReservoir.zip)
[CrookedTown.zip](https://github.com/majestic53/libanvil/files/4766058/CrookedTown.zip)
