### ISSUE TITLE
Unknown tag type in Minecraft 1.15.2 files

### ISSUE THREAD

**Issue by siarsky** [majestic53/libanvil#7]
I am not sure, if all problems in this category are linked to missing "AddBlock" tags... so I've opened this one as well.

The following tags in Minecraft 1.15.2 files are not supported by libanvil library:
region/r.-4.-2.mca
Unknown tag type: \237

region/r.0.-1.mca
Unknown tag type: k

region/r.-2.-2.mca
Unknown tag type: S

region/r.0.1.mca
Unknown tag type: \300

DIM1/region/r.-6.-3.mca
Unknown tag type: \334

DIM1/region/r.6.-5.mca
Unknown tag type: \220

DIM1/region/r.6.-4.mca
Unknown tag type: I

DIM1/region/r.-2.4.mca
Unknown tag type: \304

DIM1/region/r.5.-3.mca
Unknown tag type: \357

DIM1/region/r.5.-4.mca
Unknown tag type: \232

DIM1/region/r.-1.-1.mca
Unknown tag type: \230

DIM1/region/r.3.-2.mca
Unknown tag type: \335

DIM1/region/r.1.-1.mca
Unknown tag type: R

How to reproduce:
Run libanvil on the files in the attachment.

[mca_files.zip](https://github.com/majestic53/libanvil/files/4432562/mca_files.zip)

**Comment by majestic53** [comment]
Hi siarsky,

Let me know if the patch for [issue 6](https://github.com/majestic53/libanvil/issues/6) (b062732c64cc2819931b0ae1dc7d24bd01b674a6) addresses this issue. I was not able to reproduce this failure with that fix in-place.

Thanks,
David J

**Comment by siarsky** [comment]
Hi David,

you are right, I do not observe this issue after #6 was fixed.

Thanks
Brani
